// =====================================================================
// Contexte stable injecté dans chaque appel au coach.
// Server only, n'est pas embarqué dans le bundle front.
// Mis à jour post-op (06/07/2026, J+7) : chirurgie du 29/06/2026,
// protocole Palmieri DT4, plan BFR, calendrier, logistique Asie.
// =====================================================================

export const SURGERY_DATE = "2026-06-29";

export const USER_PROFILE = `Julien, homme né en mars 1979, 47 ans, 180 cm, poids autour de 94-95 kg, en baisse depuis 99.7 kg en février 2025 (et plus de 106 kg en 2015), objectif baisse continue. Le contrôle du poids n'est plus un simple objectif forme : la ménisectomie externe multiplie le risque d'arthrose par 7, la charge articulaire se gère à vie.

Historique sportif depuis la petite quarantaine. Sportif loisir avant 20 ans, puis 20 ans de quasi-inactivité, notamment à cause de problèmes au genou et au dos. Reprise sérieuse vers 38-39 ans en Thaïlande, plusieurs années de musculation et crossfit. Avant la blessure : padel régulier, boxe, trail, run. L'objectif central est le retour aux sports de pivot (padel, boxe) après ligamentoplastie, à 6 mois minimum, conditionné par le test isocinétique.

Mode de vie nomade entre Vietnam (60 %), Thaïlande (30 %), France (10 %). Travail assis, no-code, automatisation IA. La position assise prolongée reste un point de vigilance (raideur, inhibition, et désormais risque de phlébite post-op).

État de santé général solide. Cardio-métabolique : LDL un peu haut, HDL bas, glycémie limite améliorée, acide urique haut, SCORE2 2.8 %, pas de traitement. Syndrome de Gilbert bénin. Bradycardie sinusale et BAV 1er degré type cœur d'athlète, asymptomatique. Nodule thyroïdien TI-RADS 4 suivi, FNA bénigne août 2025.

Posture depuis le 20/06/2026 : mode récupération OPTIMALE. L'approche n'est plus "conservateur d'abord", la chirurgie est faite, on optimise chaque paramètre de la rééducation pour maximiser les chances de retour au sport à haute intensité. Julien est un patient informé qui lit la littérature (protocole Rothman, méta-analyses BFR) et veut être traité comme tel.

Préférences pour le coaching : esprit critique attendu, Julien ne veut pas être conforté ni flatté, il veut être challengé. Séparation claire entre faits, hypothèses et incertitudes. Step-by-step, pas de plan global déballé d'un coup. Phrases courtes, ton humain et casual, pas de jargon inutile, pas de tirets longs.`;

export const KNEE_HISTORY = `L'historique ancien, en bref. Deux traumas au genou droit il y a plus de 20 ans (tacle au foot, mauvaise réception d'un saut), jamais opérés ni rééduqués. Origine probable d'une déchirure partielle chronique du LCA et de lésions méniscales anciennes. Le 18 mai 2026, glissade en compression axiale au padel : déchirure oblique du ménisque externe (diagnostic principal), déchirure horizontale du ménisque interne, sur le LCA déjà partiellement déchiré. Essai conservateur en juin, puis décision de chirurgie après avis spécialisés en France.

LA CHIRURGIE, 29 juin 2026. Clinique Juge, Marseille, Dr Marc Palmieri, ambulatoire, AG + cathéter fémoral (analgésie périneurale continue). Acte réel : ligamentoplastie d'AUGMENTATION du LCA, pas une reconstruction pure. Palmieri a trouvé un stump du LCA natif viable, l'a préservé et augmenté avec un greffon DT4 (4 brins ischio-jambiers). Conséquences : mécanorécepteurs partiellement préservés, pronostic proprioceptif favorable, protocole DT4 standard inchangé. Geste méniscal : ménisectomie partielle BILATÉRALE (interne + externe), zones lésées en zone blanche non vascularisée, non suturables. Point de vigilance à vie : la ménisectomie externe est un facteur d'arthrose accélérée (x7, synthèse LaPrade). Charge articulaire et poids à surveiller pour toujours.

L'ÉVOLUTION J+1 à J+7 (au 06/07). J+1 : retour domicile, cathéter fémoral + pompe, cryothérapie par circulation d'eau glacée en continu, quad sets isométriques et ankle pumps introduits. J+2 : near-fall dans les escaliers, le bloc fémoral masquait la faiblesse du quad, fausse confiance, zéro dommage mais leçon retenue. J+3 : retrait du cathéter, antalgie par paliers (paracétamol, +néfopam, Izalgi si besoin, plafond 4 g/j), mobilisation patellaire introduite. J+4 : quad set progresse de 5 vers 10 s. J+5 : poussée inflammatoire, trois facteurs cumulés (2h30 d'escaliers, alcool, progression trop rapide des exos). J+6 : retour à 5 s, repos actif, régression de l'inflammation. J+7 : état stable, mobilisation patellaire quasi indolore, iso quad 10 s, extension passive fluide. Prochain jalon fonctionnel : 5 SLR consécutifs genou verrouillé, critère officiel de reprise d'appui.

LES LEÇONS DE LA SEMAINE 1, à réutiliser dans le coaching : le bloc analgésique crée un angle mort proprioceptif ; la progression est criteriée, pas calendaire ; une seule variable de progression à la fois, avec rationale explicite ; alcool + fatigue + station debout prolongée = cocktail interdit en phase aiguë.

TRAITEMENT. Célécoxib et Lovenox terminés à J+7 (06/07) : le risque de phlébite persiste plusieurs semaines SANS couverture anticoagulante, vigilance maximale, surtout autour du vol long-courrier. Pantoprazole terminé aussi. En cours : antalgie modulable (paracétamol, néfopam, Izalgi en dernier recours), vitamine C 1 g/j jusqu'à J+30, créatine et collagène. Oméga-3 à reprendre maintenant que le célécoxib est fini. Izalgi contient un opioïde faible : à déclarer ou éviter à la douane vietnamienne.

LE PROTOCOLE PALMIERI DT4, 5 phases, l'app est numérotée pareil. Phase I (J4-J21) : verrouillage en extension, mobilisation patellaire, mobilisation douce, chaîne fermée légère, cryothérapie. Contraintes dures : secteur protégé 0-90° pendant 3 semaines, cannes 15 jours, appui complet seulement après 5 SLR verrouillés. Phase II (J22-J45) : mobilité active sans forcer, co-contraction, rééducation de la marche, vélo dès que possible, proprio dans l'axe fin du 1er mois, balnéo fin de phase. Phase III (J45-J90) : force progressive, presse/demi-squats/stepper secteur 30-90°, isométrie longue, ischios chaîne fermée avec prudence sur le site de prélèvement DT4, balnéo. Phase IV (J90-M4) : montée en charge et proprio, surveillance de la trophicité. Phase V (M4-M6) : charge importante, proprio sur plan instable, course sur tapis, pliométrie et changements d'appui en milieu de phase. Repères de reprise : natation dans l'axe et vélo route à M1,5-2, course terrain stable M3-4, sports de pivot à 6 mois après validation isocinétique.

LE PLAN BFR, décidé le 06/07, outil principal contre l'atrophie du quadriceps pendant la fenêtre sans charge lourde (semaines 3 à 16). Base : protocole Rothman post-ACL, méta-analyses Hughes/Iversen/Ohta. Principe : cuff pneumatique proximale, charge légère 20-30 % du 1RM, gains comparables à 70-80 %. Tout se prescrit en % de LOP (Limb Occlusion Pressure), jamais en pression absolue : 40-50 % au début, progression 60-80 %. Matériel : SAGA BFR Cuffs 2.0 jambes (~349 €, Sport-Protech), auto-calibration LOP via app Bluetooth, choisi pour l'usage solo au Vietnam. Format Rothman phase 1 (dès J+14 si feu vert Palmieri le 15/07) : 5 exos enchaînés cuff gonflée en continu (SLR, SLR latéral, terminal knee extension, curls ischios légers, leg press légère), 3x15, 30 s de repos, plafond dur 30 minutes de cuff. Phase 2 Rothman (S7-S12) : long-arc quads, body squat, step-ups, RDL, heel taps latéraux. Phase 3 (M3-4) : BFR en finisseur, la charge lourde reprend le premier rôle. Plan B si Palmieri refuse le côté opéré : BFR jambe saine uniquement, contre l'asymétrie de force. Sécurité : signes de phlébite = arrêt immédiat et consultation ; douleur inhabituelle ou paresthésies sous la cuff = dégonflage immédiat et vérification de la LOP à la séance suivante.

LE CALENDRIER. 15/07/2026 : RDV Palmieri Aubagne (J+15), levée pansement, feu vert phase II, question BFR (posture patient informé, référence Rothman, chiffres précis, rappel de la contrainte 0-90°), et arbitrage de la date de vol France-Vietnam (assis prolongé = risque phlébite majoré, sans Lovenox). Fin juillet : retour Ho Chi Minh City, base rééducation ~3 mois, père kinésithérapeute en coaching à distance (session hebdo minimum), accès piscine et tapis. Attention : le père est de l'ancienne école et ne connaît pas le BFR, ce volet reste piloté par Rothman + validation Palmieri. 12/08/2026 : RDV Palmieri J+45, passage phase III, présentiel ou visio à négocier dès le 15/07. Fin août : Palmieri en congés, relais = père kiné ou professionnel local. Novembre-décembre : transition Chiang Mai (1-2 mois), bonne offre de kinés du sport expat. Fin novembre (J+5 mois) : test isocinétique à faire EN AMONT dans un centre équipé (hypothèses : retour France, Vinmec HCMC à vérifier, Bangkok Hospital/Bumrungrad à vérifier), résultats lus par le Dr Pascal Boissinot qui ne pratique pas le test lui-même. Cibles : déficit quadriceps < 10 % vs côté sain, ratio ischios/quadriceps > 0.6. Ce test conditionne la reprise des sports de pivot. Fin janvier 2027 (J+7 mois) : contrôle Boissinot post-reprise.

LOGISTIQUE. Pas de couverture Sécu française, tout est payé out-of-pocket. Kiné local anglophone/francophone à identifier à HCMC (pistes : Family Medical Practice, Vinmec), salle avec presse pour la phase III. Matériel pour le Vietnam : cuffs SAGA, genouillère cryo à circulation d'eau glacée, mètre-ruban pour la circonférence de cuisse, traitement complet, compléments.

SIGNAUX D'ALERTE prioritaires en post-op : signes de phlébite (mollet/jambe douloureuse, gonflée, chaude) surtout depuis l'arrêt du Lovenox ; fièvre ou cicatrice inflammatoire/qui coule (infection, urgence) ; perte brutale d'extension qui ne cède pas (suspicion cyclope ou blocage) ; épanchement ou douleur qui montent de jour en jour ; douleur d'interligne à la charge (zones de ménisectomie).`;

export const COACH_ROLE = `Tu es un coach médico-sportif spécialisé en rééducation post-opératoire du genou (ligamentoplastie LCA + ménisectomie). Tu accompagnes Julien au quotidien sur les 6 mois de son protocole. Tu es direct, factuel, jamais flatteur. Tu sépares clairement faits, hypothèses et incertitudes. Tu références des points de données précis (dates, valeurs, tendances) quand tu analyses. Tu connais le protocole Palmieri DT4, le plan BFR Rothman et le calendrier de Julien : tu rattaches tes conseils à la phase en cours et aux contraintes actives (secteur protégé, appui, plafonds BFR). Tu surveilles spontanément les signaux d'alerte (phlébite, infection, cyclope, épanchement) et tu recommandes de consulter quand les données le justifient. Tu rappelles les leçons de la semaine 1 quand Julien montre des signes de sur-progression : une variable à la fois, criteriée, pas calendaire. Tu réponds en français, ton humain casual, phrases courtes, pas de tirets longs. Tu donnes ton avis tranché quand c'est demandé. Tu ne remplaces ni Palmieri ni un médecin, et tu le dis quand la question dépasse ton rôle.`;
